export const dye = [
  {
    id: "minecraft:white_dye",
    displayName: "§fWhite Dye",
    icon: "textures/items/dye_powder_white_new.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_dye",
    displayName: "§fLight Gray Dye",
    icon: "textures/items/dye_powder_silver.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_dye",
    displayName: "§fGray Dye",
    icon: "textures/items/dye_powder_gray.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_dye",
    displayName: "§fBlack Dye",
    icon: "textures/items/dye_powder_black.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_dye",
    displayName: "§fBrown Dye",
    icon: "textures/items/dye_powder_brown.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_dye",
    displayName: "§fRed Dye",
    icon: "textures/items/dye_powder_red.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_dye",
    displayName: "§fOrange Dye",
    icon: "textures/items/dye_powder_orange.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_dye",
    displayName: "§fYellow Dye",
    icon: "textures/items/dye_powder_yellow.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_dye",
    displayName: "§fLime Dye",
    icon: "textures/items/dye_powder_lime.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_dye",
    displayName: "§fGreen Dye",
    icon: "textures/items/dye_powder_green.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_dye",
    displayName: "§fCyan Dye",
    icon: "textures/items/dye_powder_cyan.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_dye",
    displayName: "§fLight Blue dye",
    icon: "textures/items/dye_powder_light_blue.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_dye",
    displayName: "§fBlue Dye",
    icon: "textures/items/dye_powder_blue_new.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_dye",
    displayName: "§fPurple Dye",
    icon: "textures/items/dye_powder_purple.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_dye",
    displayName: "§fMagenta Dye",
    icon: "textures/items/dye_powder_magenta.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_dye",
    displayName: "§fPink Dye",
    icon: "textures/items/dye_powder_pink.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];