export const miscellaneous = [
  {
    id: "minecraft:name_tag",
    displayName: "§fName Tag",
    icon: "textures/items/name_tag.png",
    basePrice: 580,
    stockMax: 64,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 4.0,
    demandWindowSize: 1,
    restockAmount: 32,
    cannotBeSold: true,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:lead",
    displayName: "§fLead",
    icon: "textures/items/lead.png",
    basePrice: 18,
    stockMax: 128,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 64,
    cannotBeSold: true,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:saddle",
    displayName: "§fSaddle",
    icon: "textures/items/saddle.png",
    basePrice: 20,
    stockMax: 128,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 64,
    cannotBeSold: true,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:water_bucket",
    displayName: "§fWater Bucket",
    icon: "textures/items/bucket_water.png",
    basePrice: 41,
    stockMax: 27,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 7,
    cannotBeSold: true,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:lava_bucket",
    displayName: "§fLava Bucket",
    icon: "textures/items/bucket_lava.png",
    basePrice: 92,
    stockMax: 27,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 7,
    cannotBeSold: true,
    restockIntervalMinutes: 12
  },
  {
    id: "minecraft:totem_of_undying",
    displayName: "§fTotem Of Undying",
    icon: "textures/items/totem.png",
    basePrice: 6098,
    stockMax: 135,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 54,
    cannotBeSold: true,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:beacon",
    displayName: "§f§5Beacon§r",
    icon: "textures/blocks/beacon.png",
    basePrice: 1000000,
    rarityFactor: 3.5,
    _fp: 0.07,
    _tc: 0.60,
    stockMax: 2,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 1,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:shears",
    displayName: "§fShears",
    icon: "textures/items/shears.png",
    basePrice: 90,
    stockMax: 32,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 16,
    cannotBeSold: true,
    restockIntervalMinutes: 5
  },
  {
    id: "minecraft:flint_and_steel",
    displayName: "§fFlint & Steel",
    icon: "textures/items/flint_and_steel.png",
    basePrice: 80,
    stockMax: 32,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 16,
    cannotBeSold: true,
    restockIntervalMinutes: 5
  },
  {
    id: "minecraft:compass",
    displayName: "§fCompass",
    icon: "textures/items/compass_item.png",
    basePrice: 81,
    stockMax: 32,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 16,
    cannotBeSold: true,
    restockIntervalMinutes: 5
  },
  {
    id: "minecraft:spyglass",
    displayName: "§fSpyglass",
    icon: "textures/items/spyglass.png",
    basePrice: 98,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 10
    },
  {
    id: "minecraft:elytra",
    displayName: "§f§5Elytra§r",
    icon: "textures/items/elytra.png",
    basePrice: 3000000,
    rarityFactor: 3.5,
    _fp: 0.08,
    _tc: 0.63,
    stockMax: 2,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 3.0,
    demandWindowSize: 1,
    restockAmount: 1,
    restockIntervalMinutes: 30
  }
];