export const tools = [
 {
    id: "minecraft:iron_sword",
    displayName: "§fIron Sword",
    icon: "textures/items/iron_sword.png",
    basePrice: 428,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:iron_axe",
    displayName: "§fIron Axe",
    icon: "textures/items/iron_axe.png",
    basePrice: 438,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:iron_pickaxe",
    displayName: "§fIron Pickaxe",
    icon: "textures/items/iron_pickaxe.png",
    basePrice: 438,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:iron_shovel",
    displayName: "§fIron Shovel",
    icon: "textures/items/iron_shovel.png",
    basePrice: 418,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:diamond_sword",
    displayName: "§fDiamond Sword",
    icon: "textures/items/diamond_sword.png",
    basePrice: 3850,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:diamond_axe",
    displayName: "§fDiamond Axe",
    icon: "textures/items/diamond_axe.png",
    basePrice: 3950,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:diamond_pickaxe",
    displayName: "§fdiamond_pickaxe",
    icon: "textures/items/diamond_pickaxe.png",
    basePrice: 3950,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:diamond_shovel",
    displayName: "§fdiamond_shovel",
    icon: "textures/items/diamond_shovel.png",
    basePrice: 3750,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:netherite_sword",
    displayName: "§fNetherite Sword",
    icon: "textures/items/netherite_sword.png",
    basePrice: 17380,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 30
  },
  {
    id: "minecraft:netherite_axe",
    displayName: "§fNetherite Axe",
    icon: "textures/items/netherite_axe.png",
    basePrice: 17580,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 30
  },
  {
    id: "minecraft:netherite_pickaxe",
    displayName: "§fNetherite Pickaxe",
    icon: "textures/items/netherite_pickaxe.png",
    basePrice: 17580,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 30
  },
  {
    id: "minecraft:netherite_shovel",
    displayName: "§fNetherite Shovel",
    icon: "textures/items/netherite_shovel.png",
    basePrice: 8690,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 0.1,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 30
  },
  {
    id: "minecraft:mace",
    displayName: "§5Mace§r",
    icon: "textures/items/mace.png",
    basePrice: 1000000,
    rarityFactor: 2.5,
    _fp: 0.07,
    _tc: 0.62,
    stockMax: 2,
    priceFloorPercent: 0.25,
    priceCeilingPercent: 8.0,
    demandWindowSize: 40,
    restockAmount: 1,
    restockIntervalMinutes: 720
  }
];