export const armor = [
 {
    id: "minecraft:iron_helmet",
    displayName: "§fIron Helmet",
    icon: "textures/items/iron_helmet.png",
    basePrice: 2070,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:iron_chestplate",
    displayName: "§fIron Chestplate",
    icon: "textures/items/iron_chestplate.png",
    basePrice: 2712,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:iron_leggings",
    displayName: "§fIron Leggings",
    icon: "textures/items/iron_leggings.png",
    basePrice: 2498,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:iron_boots",
    displayName: "§fIron Boots",
    icon: "textures/items/iron_boots.png",
    basePrice: 1856,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 256,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:diamond_helmet",
    displayName: "§fDiamond Helmet",
    icon: "textures/items/diamond_helmet.png",
    basePrice: 19625,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:diamond_chestplate",
    displayName: "§fDiamond Chestplate",
    icon: "textures/items/diamond_chestplate.png",
    basePrice: 25400,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:diamond_leggings",
    displayName: "§fDiamond Leggings",
    icon: "textures/items/diamond_leggings.png",
    basePrice: 23475,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:diamond_boots",
    displayName: "§fDiamond Boots",
    icon: "textures/items/diamond_boots.png",
    basePrice: 17700,
    stockMax: 16,
    priceFloorPercent: 0.05,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:netherite_helmet",
    displayName: "§fNetherite Helmet",
    icon: "textures/items/netherite_helmet.png",
    basePrice: 53450,
    stockMax: 16,
    priceFloorPercent: 0.05,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:netherite_chestplate",
    displayName: "§fNetherite Chestplate",
    icon: "textures/items/netherite_chestplate.png",
    basePrice: 69520,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:netherite_leggings",
    displayName: "§fNetherite Leggings",
    icon: "textures/items/netherite_leggings.png",
    basePrice: 60830,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:netherite_boots",
    displayName: "§fNetherite Boots",
    icon: "textures/items/netherite_boots.png",
    basePrice: 51760,
    stockMax: 16,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 8,
    cannotBeSold: true,
    restockIntervalMinutes: 15
  }
];