export const glassBlock = [
 {
    id: "minecraft:glass",
    displayName: "§fGlass",
    icon: "textures/blocks/glass.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:white_stained_glass",
    displayName: "§fWhite Stained Glass",
    icon: "textures/blocks/glass_white.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_stained_glass",
    displayName: "§fLight Gray Stained Glass",
    icon: "textures/blocks/glass_silver.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_stained_glass",
    displayName: "§fGray Stained Glass",
    icon: "textures/blocks/glass_gray.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_stained_glass",
    displayName: "§fBlack Stained Glass",
    icon: "textures/blocks/glass_black.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_stained_glass",
    displayName: "§fBrown Stained Glass",
    icon: "textures/blocks/glass_brown.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_stained_glass",
    displayName: "§fRed Stained Glass",
    icon: "textures/blocks/glass_red.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_stained_glass",
    displayName: "§fOrange Stained Glass",
    icon: "textures/blocks/glass_orange.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_stained_glass",
    displayName: "§fYellow Stained Glass",
    icon: "textures/blocks/glass_yellow.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_stained_glass",
    displayName: "§fLime Stained Glass",
    icon: "textures/blocks/glass_lime.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_stained_glass",
    displayName: "§fGreen Stained Glass",
    icon: "textures/blocks/glass_green.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_stained_glass",
    displayName: "§fCyan Stained Glass",
    icon: "textures/blocks/glass_cyan.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_stained_glass",
    displayName: "§fLight Blue Stained Glass",
    icon: "textures/blocks/glass_light_blue.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_stained_glass",
    displayName: "§fBlue Stained Glass",
    icon: "textures/blocks/glass_blue.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_stained_glass",
    displayName: "§fPurple Stained Glass",
    icon: "textures/blocks/glass_purple.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_stained_glass",
    displayName: "§fMagenta Stained Glass",
    icon: "textures/blocks/glass_magenta.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_stained_glass",
    displayName: "§fPink Stained Glass",
    icon: "textures/blocks/glass_pink.png",
    basePrice: 34,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];