export const mobd = [
 {
    id: "minecraft:rotten_flesh",
    displayName: "§fRotten Flesh",
    icon: "textures/items/rotten_flesh.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 512,
    restockIntervalMinutes: 5
  },
  {
    id: "minecraft:bone",
    displayName: "§fBone",
    icon: "textures/items/bone.png",
    basePrice: 34,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 256,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:spider_eye",
    displayName: "§fSpider Eye",
    icon: "textures/items/spider_eye.png",
    basePrice: 48,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 256,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:string",
    displayName: "§fString",
    icon: "textures/items/string.png",
    basePrice: 35,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 256,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:gunpowder",
    displayName: "§fGunpowder",
    icon: "textures/items/gunpowder.png",
    basePrice: 178,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 256,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:leather",
    displayName: "§fLeather",
    icon: "textures/items/leather.png",
    basePrice: 20,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 256,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:blaze_rod",
    displayName: "§fBlaze Rod",
    icon: "textures/items/blaze_rod.png",
    basePrice: 474,
    stockMax: 256,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 128,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:breeze_rod",
    displayName: "§fBreeze Rod",
    icon: "textures/items/breeze_rod.png",
    basePrice: 598,
    stockMax: 256,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 128,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:magma_cream",
    displayName: "§fMagma Cream",
    icon: "textures/items/magma_cream.png",
    basePrice: 856,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 128,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:ghast_tear",
    displayName: "§fGhast Tear",
    icon: "textures/items/ghast_tear.png",
    basePrice: 1478,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 64,
    restockIntervalMinutes: 18
  },
  {
    id: "minecraft:ender_pearl",
    displayName: "§fEnder Pearl",
    icon: "textures/items/ender_pearl.png",
    basePrice: 376,
    stockMax: 256,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 10,
    restockAmount: 128,
    restockIntervalMinutes: 12
  }
];