export const farm = [
 {
    id: "minecraft:wheat",
    displayName: "§fWheat",
    icon: "textures/items/wheat.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:beetroot",
    displayName: "§fBeetroot",
    icon: "textures/items/beetroot.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:potato",
    displayName: "§fPotato",
    icon: "textures/items/potato.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:carrot",
    displayName: "§fCarrot",
    icon: "textures/items/carrot.png",
    basePrice: 28,
    stockMax: 1024,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:melon_block",
    displayName: "§fMelon",
    icon: "textures/icon/farm/melon_3d.png",
    basePrice: 78,
    stockMax: 512,
    priceFloorPercent: 0.35,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:pumpkin",
    displayName: "§fPumpkin",
    icon: "textures/icon/farm/pumpkin_3d.png",
    basePrice: 78,
    stockMax: 512,
    priceFloorPercent: 0.35,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:melon_slice",
    displayName: "§fMelon Slice",
    icon: "textures/items/melon.png",
    basePrice: 8,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:sweet_berries",
    displayName: "§fSweet Berries",
    icon: "textures/items/sweet_berries.png",
    basePrice: 36,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:glow_berries",
    displayName: "§fglow_berries",
    icon: "textures/items/glow_berries.png",
    basePrice: 38,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:kelp",
    displayName: "§fKelp",
    icon: "textures/items/kelp.png",
    basePrice: 32,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:sugar_cane",
    displayName: "§fSugar Cane",
    icon: "textures/items/reeds.png",
    basePrice: 30,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:bamboo",
    displayName: "§fBamboo",
    icon: "textures/items/bamboo.png",
    basePrice: 40,
    stockMax: 512,
    priceFloorPercent: 0.3,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:sea_pickle",
    displayName: "§fSea Pickle",
    icon: "textures/items/sea_pickle.png",
    basePrice: 105,
    stockMax: 512,
    priceFloorPercent: 0.4,
    priceCeilingPercent: 0.75,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  }
];