export const concrete = [
  {
    id: "minecraft:white_concrete",
    displayName: "§fWhite Concrete",
    icon: "textures/icon/blocks/white_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_concrete",
    displayName: "§fLight Gray Concrete",
    icon: "textures/icon/blocks/light_gray_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_concrete",
    displayName: "§fGray Concrete",
    icon: "textures/icon/blocks/gray_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_concrete",
    displayName: "§fBlack Concrete",
    icon: "textures/icon/blocks/black_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_concrete",
    displayName: "§fBrown Concrete",
    icon: "textures/icon/blocks/brown_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_concrete",
    displayName: "§fRed Concrete",
    icon: "textures/icon/blocks/red_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_concrete",
    displayName: "§fOrange Concrete",
    icon: "textures/icon/blocks/orange_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_concrete",
    displayName: "§fYellow Concrete",
    icon: "textures/icon/blocks/yellow_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_concrete",
    displayName: "§fLime Concrete",
    icon: "textures/icon/blocks/lime_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_concrete",
    displayName: "§fGreen Concrete",
    icon: "textures/icon/blocks/green_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_concrete",
    displayName: "§fCyan Concrete",
    icon: "textures/icon/blocks/cyan_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_concrete",
    displayName: "§fLight Blue Concrete",
    icon: "textures/icon/blocks/light_blue_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_concrete",
    displayName: "§fBlue Concrete",
    icon: "textures/icon/blocks/blue_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_concrete",
    displayName: "§fPurple Concrete",
    icon: "textures/icon/blocks/purple_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_concrete",
    displayName: "§fMagenta Concrete",
    icon: "textures/icon/blocks/magenta_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_concrete",
    displayName: "§fPink Concrete",
    icon: "textures/icon/blocks/pink_concrete_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];