export const decorativeStone = [
  {
    id: "minecraft:stone_bricks",
    displayName: "§fStone Bricks",
    icon: "textures/icon/blocks/stone_bricks_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:mossy_stone_bricks",
    displayName: "§fMossy Stone Bricks",
    icon: "textures/icon/blocks/mossy_stone_bricks_3d.png",
    basePrice: 21,
    stockMax: 1024,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cracked_stone_bricks",
    displayName: "§fCracked Stone Bricks",
    icon: "textures/icon/blocks/cracked_stone_bricks_3d.png",
    basePrice: 21,
    stockMax: 1024,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:chiseled_stone_bricks",
    displayName: "§fChiseled Stone Bricks",
    icon: "textures/icon/blocks/chiseled_stone_bricks_3d.png",
    basePrice: 21,
    stockMax: 1024,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:smooth_stone",
    displayName: "§fSmooth Stone",
    icon: "textures/icon/blocks/smooth_stone_3d.png",
    basePrice: 19,
    stockMax: 1024,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:end_stone_bricks",
    displayName: "§fEnd Stone Bricks",
    icon: "textures/icon/blocks/end_stone_bricks_3d.png",
    basePrice: 40,
    stockMax: 728,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 18
  },
  {
    id: "minecraft:polished_blackstone_bricks",
    displayName: "§fPolished Blackstone Bricks",
    icon: "textures/icon/blocks/polished_blackstone_bricks_3d.png",
    basePrice: 44,
    rarityFactor: 1.3,
    stockMax: 728,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 25
  },
  {
    id: "minecraft:cracked_polished_blackstone_bricks",
    displayName: "§fCracked Polished Blackstone",
    icon: "textures/icon/blocks/cracked_polished_blackstone_bricks_3d.png",
    basePrice: 45,
    rarityFactor: 1.3,
    stockMax: 728,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 25
  },
  {
    id: "minecraft:gilded_blackstone",
    displayName: "§fGilded Blackstone",
    icon: "textures/icon/blocks/gilded_blackstone_3d.png",
    basePrice: 50,
    rarityFactor: 1.4,
    stockMax: 512,
    priceFloorPercent: 0.05,
    priceCeilingPercent: 2.5,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:chiseled_polished_blackstone",
    displayName: "§fChiseled Polished Blackstone",
    icon: "textures/icon/blocks/chiseled_polished_blackstone_3d.png",
    basePrice: 45,
    rarityFactor: 1.3,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:deepslate_tiles",
    displayName: "§fDeepslate Tiles",
    icon: "textures/icon/blocks/deepslate_tiles_3d.png",
    basePrice: 36,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:cracked_deepslate_tiles",
    displayName: "§fCracked Deepslate Tiles",
    icon: "textures/icon/blocks/cracked_deepslate_tiles_3d.png",
    basePrice: 36,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:deepslate_bricks",
    displayName: "§fDeepslate Bricks",
    icon: "textures/icon/blocks/deepslate_bricks_3d.png",
    basePrice: 36,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:tuff_bricks",
    displayName: "§fTuff Bricks",
    icon: "textures/icon/blocks/tuff_bricks_3d.png",
    basePrice: 35,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:cracked_deepslate_bricks",
    displayName: "§fCracked Deepslate Bricks",
    icon: "textures/icon/blocks/cracked_deepslate_bricks_3d.png",
    basePrice: 36,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:chiseled_deepslate",
    displayName: "§fChiseled Deepslate",
    icon: "textures/icon/blocks/chiseled_deepslate_3d.png",
    basePrice: 36,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:chiseled_tuff",
    displayName: "§fChiseled Tuff",
    icon: "textures/icon/blocks/chiseled_tuff_3d.png",
    basePrice: 35,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:chiseled_tuff_bricks",
    displayName: "§fChiseled Tuff Bricks",
    icon: "textures/icon/blocks/chiseled_tuff_bricks_3d.png",
    basePrice: 35,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  }
];