export const functionalBlock = [
  {
    id: "minecraft:cartography_table",
    displayName: "§fCartography Table",
    icon: "textures/icon/blocks/cartography_table_3d.png",
    basePrice: 36,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:fletching_table",
    displayName: "§fFletching Table",
    icon: "textures/icon/blocks/fletching_table_3d.png",
    basePrice: 36,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:smithing_table",
    displayName: "§fSmithing Table",
    icon: "textures/icon/blocks/smithing_table_3d.png",
    basePrice: 36,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:furnace",
    displayName: "§fFurnace",
    icon: "textures/icon/blocks/furnace_3d.png",
    basePrice: 40,
    stockMax: 64,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 32,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:blast_furnace",
    displayName: "§fBlast Furnace",
    icon: "textures/icon/blocks/blast_furnace_3d.png",
    basePrice: 56,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:respawn_anchor",
    displayName: "§fAnchor",
    icon: "textures/icon/blocks/anchor_3d.png",
    basePrice: 4050,
    stockMax: 768,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brewing_stand",
    displayName: "§fBrewing Stand",
    icon: "textures/icon/blocks/brewing_stand_3d.png",
    basePrice: 59,
    rarityFactor: 1.1,
    stockMax: 128,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.2,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 12
  },
  {
    id: "minecraft:anvil",
    displayName: "§fAnvil",
    icon: "textures/icon/blocks/anvil_3d.png",
    basePrice: 64,
    stockMax: 256,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 128,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:grindstone",
    displayName: "§fGrindstone",
    icon: "textures/icon/blocks/grindstone_3d.png",
    basePrice: 52,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:enchanting_table",
    displayName: "§fEnchanting Table",
    icon: "textures/icon/blocks/enchanting_table_3d.png",
    basePrice: 1520,
    stockMax: 64,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 32,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:bookshelf",
    displayName: "§fBookshelf",
    icon: "textures/icon/blocks/bookshelf_3d.png",
    basePrice: 90,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:chiseled_bookshelf",
    displayName: "§fChiseled Bookshelf",
    icon: "textures/icon/blocks/chiseled_bookshelf_3d.png",
    basePrice: 84,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:lectern",
    displayName: "§fLectern",
    icon: "textures/icon/blocks/lectern_3d.png",
    basePrice: 52,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:smoker",
    displayName: "§fSmoker",
    icon: "textures/icon/blocks/smoker_3d.png",
    basePrice: 38,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:ender_chest",
    displayName: "§fEnd Chest",
    icon: "textures/icon/blocks/end_chest_3d.png",
    basePrice: 520,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:cauldron",
    displayName: "§fCauldron",
    icon: "textures/icon/blocks/cauldron_3d.png",
    basePrice: 42,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:composter",
    displayName: "§fComposter",
    icon: "textures/icon/blocks/composter_3d.png",
    basePrice: 30,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:chest",
    displayName: "§fChest",
    icon: "textures/icon/blocks/chest_3d.png",
    basePrice: 34,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 18
  },
  {
    id: "minecraft:barrel",
    displayName: "§fBarrel",
    icon: "textures/icon/blocks/barrel_3d.png",
    basePrice: 34,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:shulker_box",
    displayName: "§fShulker Box",
    icon: "textures/icon/blocks/shulker_3d.png",
    basePrice: 3560,
    stockMax: 64,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 32,
    restockIntervalMinutes: 60
  },
  {
    id: "minecraft:stonecutter",
    displayName: "§fStonecutter",
    icon: "textures/icon/blocks/stonecutter_3d.png",
    basePrice: 38,
    stockMax: 128,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 10
  }
];