export const glazedTerracotta = [
  {
    id: "minecraft:white_glazed_terracotta",
    displayName: "§fWhite Glazed Terracotta",
    icon: "textures/icon/blocks/white_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_glazed_terracotta",
    displayName: "§fLight Gray Glazed Terracotta",
    icon: "textures/icon/blocks/light_gray_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_glazed_terracotta",
    displayName: "§fGray Glazed Terracotta",
    icon: "textures/icon/blocks/gray_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_glazed_terracotta",
    displayName: "§fBlack Glazed Terracotta",
    icon: "textures/icon/blocks/black_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_glazed_terracotta",
    displayName: "§fBrown Glazed Terracotta",
    icon: "textures/icon/blocks/brown_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_glazed_terracotta",
    displayName: "§fRed Glazed Terracotta",
    icon: "textures/icon/blocks/red_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_glazed_terracotta",
    displayName: "§fOrange Glazed Terracotta",
    icon: "textures/icon/blocks/orange_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_glazed_terracotta",
    displayName: "§fYellow Glazed Terracotta",
    icon: "textures/icon/blocks/yellow_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_glazed_terracotta",
    displayName: "§fLime Glazed Terracotta",
    icon: "textures/icon/blocks/lime_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_glazed_terracotta",
    displayName: "§fGreen Glazed Terracotta",
    icon: "textures/icon/blocks/green_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_glazed_terracotta",
    displayName: "§fCyan Glazed Terracotta",
    icon: "textures/icon/blocks/cyan_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_glazed_terracotta",
    displayName: "§fLight Blue Glazed Terracotta",
    icon: "textures/icon/blocks/light_blue_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_glazed_terracotta",
    displayName: "§fBlue Glazed Terracotta",
    icon: "textures/icon/blocks/blue_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_glazed_terracotta",
    displayName: "§fPurple Glazed Terracotta",
    icon: "textures/icon/blocks/purple_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_glazed_terracotta",
    displayName: "§fMagenta Glazed Terracotta",
    icon: "textures/icon/blocks/magenta_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_glazed_terracotta",
    displayName: "§fPink Glazed Terracotta",
    icon: "textures/icon/blocks/pink_glazed_terracotta_3d.png",
    basePrice: 32,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];