export const logs = [
  {
    id: "minecraft:oak_log",
    displayName: "§fOak Log",
    icon: "textures/icon/blocks/oak_log_3d.png",
    basePrice: 12,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:birch_log",
    displayName: "§fBirch Log",
    icon: "textures/icon/blocks/birch_log_3d.png",
    basePrice: 12,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:spruce_log",
    displayName: "§fSpruce Log",
    icon: "textures/icon/blocks/spruce_log_3d.png",
    basePrice: 12,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:jungle_log",
    displayName: "§fJungle Log",
    icon: "textures/icon/blocks/jungle_log_3d.png",
    basePrice: 12,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:acacia_log",
    displayName: "§fAcacia Log",
    icon: "textures/icon/blocks/acacia_log_3d.png",
    basePrice: 12,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:dark_oak_log",
    displayName: "§fDark Oak Log",
    icon: "textures/icon/blocks/dark_oak_log_3d.png",
    basePrice: 14,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:mangrove_log",
    displayName: "§fMangrove Log",
    icon: "textures/icon/blocks/mangrove_log_3d.png",
    basePrice: 16,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:cherry_log",
    displayName: "§fCherry Log",
    icon: "textures/icon/blocks/cherry_log_3d.png",
    basePrice: 16,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:pale_oak_log",
    displayName: "§fPale Oak Log",
    icon: "textures/icon/blocks/pale_oak_log_3d.png",
    basePrice: 18,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:crimson_stem",
    displayName: "§fCrimson Stem",
    icon: "textures/icon/blocks/crimson_log_3d.png",
    basePrice: 20,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 28
  },
  {
    id: "minecraft:warped_stem",
    displayName: "§fWarped Stem",
    icon: "textures/icon/blocks/warped_log_3d.png",
    basePrice: 20,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 1,
    restockAmount: 256,
    restockIntervalMinutes: 28
  }
];