export const otherBlock = [
  {
    id: "minecraft:crimson_nylium",
    displayName: "§fCrimson Nylium",
    icon: "textures/icon/blocks/crimson_nylium_3d.png",
    basePrice: 28,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.4,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:warped_nylium",
    displayName: "§fWarped Nylium",
    icon: "textures/icon/blocks/warped_nylium_3d.png",
    basePrice: 28,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.4,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:netherrack",
    displayName: "§fNetherrack",
    icon: "textures/icon/blocks/netherrack_3d.png",
    basePrice: 8,
    rarityFactor: 0.8,
    stockMax: 2048,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 0.8,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:soul_soil",
    displayName: "§fSoul Soil",
    icon: "textures/icon/blocks/soul_soil_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:grass_block",
    displayName: "§fGrass Block",
    icon: "textures/icon/blocks/grass_block_3d.png",
    basePrice: 16,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:podzol",
    displayName: "§fPodzol",
    icon: "textures/icon/blocks/podzol_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:mycelium",
    displayName: "§fMycelium",
    icon: "textures/icon/blocks/mycelium_3d.png",
    basePrice: 20,
    stockMax: 768,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.2,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:dirt_path",
    displayName: "§fDirt Path",
    icon: "textures/icon/blocks/dirt_path_3d.png",
    basePrice: 10,
    stockMax: 2048,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:dirt",
    displayName: "§fDirt",
    icon: "textures/icon/blocks/dirt_3d.png",
    basePrice: 8,
    stockMax: 2048,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 8
  },
  {
    id: "minecraft:coarse_dirt",
    displayName: "§fCoarse Dirt",
    icon: "textures/icon/blocks/coarse_dirt_3d.png",
    basePrice: 10,
    stockMax: 2048,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:rooted_dirt",
    displayName: "§fRooted Dirt",
    icon: "textures/icon/blocks/rooted_dirt_3d.png",
    basePrice: 14,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 12
  },
  {
    id: "minecraft:mud",
    displayName: "§fMud",
    icon: "textures/icon/blocks/mud_3d.png",
    basePrice: 12,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 12
  },
  {
    id: "minecraft:clay",
    displayName: "§fClay",
    icon: "textures/icon/blocks/clay_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.2,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gravel",
    displayName: "§fGravel",
    icon: "textures/icon/blocks/gravel_3d.png",
    basePrice: 10,
    stockMax: 2048,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:sand",
    displayName: "§fSand",
    icon: "textures/icon/blocks/sand_3d.png",
    basePrice: 10,
    stockMax: 2048,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 1024,
    restockIntervalMinutes: 10
  },
  {
    id: "minecraft:red_sand",
    displayName: "§fRed Sand",
    icon: "textures/icon/blocks/red_sand_3d.png",
    basePrice: 14,
    stockMax: 1024,
    priceFloorPercent: 0.02,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 12
  },
  {
    id: "minecraft:ice",
    displayName: "§fIce",
    icon: "textures/icon/blocks/ice_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.2,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:packed_ice",
    displayName: "§fPacked Ice",
    icon: "textures/icon/blocks/packed_ice_3d.png",
    basePrice: 30,
    stockMax: 768,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.4,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:blue_ice",
    displayName: "§fBlue Ice",
    icon: "textures/icon/blocks/blue_ice_3d.png",
    basePrice: 48,
    stockMax: 384,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.5,
    demandWindowSize: 40,
    restockAmount: 192,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:dripstone_block",
    displayName: "§fDripstone Block",
    icon: "textures/icon/blocks/dripstone_block_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:moss_block",
    displayName: "§fMoss Block",
    icon: "textures/icon/blocks/moss_block_3d.png",
    basePrice: 16,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pale_moss_block",
    displayName: "§fPale Moss Block",
    icon: "textures/icon/blocks/pale_moss_block_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.1,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:muddy_mangrove_roots",
    displayName: "§fMuddy Mangrove Roots",
    icon: "textures/icon/blocks/muddy_mangrove_roots_3d.png",
    basePrice: 20,
    stockMax: 768,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.1,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:amethyst_block",
    displayName: "§fAmethyst Block",
    icon: "textures/icon/blocks/amethyst_block_3d.png",
    basePrice: 40,
    stockMax: 384,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 1.6,
    demandWindowSize: 40,
    restockAmount: 192,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:budding_amethyst",
    displayName: "§fBudding Amethyst",
    icon: "textures/icon/blocks/budding_amethyst_3d.png",
    basePrice: 45,
    stockMax: 128,
    priceFloorPercent: 0.05,
    priceCeilingPercent: 1.8,
    demandWindowSize: 40,
    restockAmount: 64,
    restockIntervalMinutes: 32
  },
  {
    id: "minecraft:obsidian",
    displayName: "§fObsidian",
    icon: "textures/icon/blocks/obsidian_3d.png",
    basePrice: 580,
    stockMax: 728,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 3.5,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  }
];