export const planks = [
  {
    id: "minecraft:oak_planks",
    displayName: "§fOak Planks",
    icon: "textures/icon/blocks/oak_planks_3d.png",
    basePrice: 4,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:birch_planks",
    displayName: "§fBirch Planks",
    icon: "textures/icon/blocks/birch_planks_3d.png",
    basePrice: 4,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:spruce_planks",
    displayName: "§fSpruce Planks",
    icon: "textures/icon/blocks/spruce_planks_3d.png",
    basePrice: 4,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:jungle_planks",
    displayName: "§fJungle Planks",
    icon: "textures/icon/blocks/jungle_planks_3d.png",
    basePrice: 4,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:acacia_planks",
    displayName: "§fAcacia Planks",
    icon: "textures/icon/blocks/acacia_planks_3d.png",
    basePrice: 4,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 16
  },
  {
    id: "minecraft:dark_oak_planks",
    displayName: "§fDark Oak Planks",
    icon: "textures/icon/blocks/dark_oak_planks_3d.png",
    basePrice: 5,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:mangrove_planks",
    displayName: "§fMangrove Planks",
    icon: "textures/icon/blocks/mangrove_planks_3d.png",
    basePrice: 6,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:cherry_planks",
    displayName: "§fCherry Planks",
    icon: "textures/icon/blocks/cherry_planks_3d.png",
    basePrice: 5,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:pale_oak_planks",
    displayName: "§fPale Oak Planks",
    icon: "textures/icon/blocks/pale_oak_planks_3d.png",
    basePrice: 6,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:bamboo_planks",
    displayName: "§fBamboo Planks",
    icon: "textures/icon/blocks/bamboo_planks_3d.png",
    basePrice: 5,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:bamboo_mosaic",
    displayName: "§fBamboo Mosaic",
    icon: "textures/icon/blocks/bamboo_mosaic_3d.png",
    basePrice: 5,
    stockMax: 512,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 24
  },
  {
    id: "minecraft:crimson_planks",
    displayName: "§fCrimson Planks",
    icon: "textures/icon/blocks/crimson_planks_3d.png",
    basePrice: 7,
    stockMax: 384,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 192,
    restockIntervalMinutes: 28
  },
  {
    id: "minecraft:warped_planks",
    displayName: "§fWarped Planks",
    icon: "textures/icon/blocks/warped_planks_3d.png",
    basePrice: 7,
    stockMax: 384,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 192,
    restockIntervalMinutes: 28
  }
];