export const stone = [
  {
    id: "minecraft:stone",
    displayName: "§fStone",
    icon: "textures/icon/blocks/stone_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.06,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:granite",
    displayName: "§fgranite",
    icon: "textures/icon/blocks/granite_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.06,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:diorite",
    displayName: "§fDiorite",
    icon: "textures/icon/blocks/diorite_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.06,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:andesite",
    displayName: "§fAndesite",
    icon: "textures/icon/blocks/andesite_3d.png",
    basePrice: 20,
    stockMax: 1024,
    priceFloorPercent: 0.06,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blackstone",
    displayName: "§fBlackstone",
    icon: "textures/icon/blocks/blackstone_3d.png",
    basePrice: 105,
    stockMax: 728,
    priceFloorPercent: 0.04,
    priceCeilingPercent: 3.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 25
  },
  {
    id: "minecraft:deepslate",
    displayName: "§fDeepslate",
    icon: "textures/icon/blocks/deepslate_3d.png",
    basePrice: 58,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:tuff",
    displayName: "§fTuff",
    icon: "textures/icon/blocks/tuff_3d.png",
    basePrice: 45,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:basalt",
    displayName: "§fBasalt",
    icon: "textures/icon/blocks/basalt_3d.png",
    basePrice: 56,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:polished_granite",
    displayName: "§fPolished Granite",
    icon: "textures/icon/blocks/polished_granite_3d.png",
    basePrice: 26,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:polished_diorite",
    displayName: "§fPolished Diorite",
    icon: "textures/icon/blocks/polished_diorite_3d.png",
    basePrice: 26,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "polished_andesite",
    displayName: "§fPolished Andesite",
    icon: "textures/icon/blocks/polished_andesite_3d.png",
    basePrice: 26,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:polished_blackstone",
    displayName: "§fPolished Blackstone",
    icon: "textures/icon/blocks/polished_blackstone_3d.png",
    basePrice: 128,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:polished_deepslate",
    displayName: "§fPolished Deepslate",
    icon: "textures/icon/blocks/polished_deepslate_3d.png",
    basePrice: 68,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:polished_tuff",
    displayName: "§fPolished Tuff",
    icon: "textures/icon/blocks/polished_tuff_3d.png",
    basePrice: 42,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:polished_basalt",
    displayName: "§fPolished Basalt",
    icon: "textures/icon/blocks/polished_basalt_3d.png",
    basePrice: 40,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  },
  {
    id: "minecraft:smooth_basalt",
    displayName: "§fSmooth Basalt",
    icon: "textures/icon/blocks/smooth_basalt_3d.png",
    basePrice: 40,
    stockMax: 728,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 2.0,
    demandWindowSize: 40,
    restockAmount: 384,
    restockIntervalMinutes: 20
  }
];