export const terracotta = [
{
    id: "minecraft:terracotta",
    displayName: "§fTerracotta",
    icon: "textures/icon/blocks/terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:white_terracotta",
    displayName: "§fWhite Terracotta",
    icon: "textures/icon/blocks/white_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_terracotta",
    displayName: "§fLight Gray Terracotta",
    icon: "textures/icon/blocks/light_gray_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_terracotta",
    displayName: "§fGray Terracotta",
    icon: "textures/icon/blocks/gray_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_terracotta",
    displayName: "§fBlack Terracotta",
    icon: "textures/icon/blocks/black_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_terracotta",
    displayName: "§fBrown Terracotta",
    icon: "textures/icon/blocks/brown_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_terracotta",
    displayName: "§fRed Terracotta",
    icon: "textures/icon/blocks/red_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_terracotta",
    displayName: "§fOrange Terracotta",
    icon: "textures/icon/blocks/orange_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_terracotta",
    displayName: "§fYellow Terracotta",
    icon: "textures/icon/blocks/yellow_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_terracotta",
    displayName: "§fLime Terracotta",
    icon: "textures/icon/blocks/lime_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_terracotta",
    displayName: "§fGreen Terracotta",
    icon: "textures/icon/blocks/green_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_terracotta",
    displayName: "§fCyan Terracotta",
    icon: "textures/icon/blocks/cyan_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_terracotta",
    displayName: "§fLight Blue Terracotta",
    icon: "textures/icon/blocks/light_blue_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_terracotta",
    displayName: "§fBlue Terracotta",
    icon: "textures/icon/blocks/blue_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_terracotta",
    displayName: "§fPurple Terracotta",
    icon: "textures/icon/blocks/purple_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_terracotta",
    displayName: "§fMagenta Terracotta",
    icon: "textures/icon/blocks/magenta_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_terracotta",
    displayName: "§fPink Terracotta",
    icon: "textures/icon/blocks/pink_terracotta_3d.png",
    basePrice: 54,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];