export const wool = [
  {
    id: "minecraft:white_wool",
    displayName: "§fWhite Wool",
    icon: "textures/icon/blocks/white_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_gray_wool",
    displayName: "§fLight Gray Wool",
    icon: "textures/icon/blocks/light_gray_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:gray_wool",
    displayName: "§fGray Wool",
    icon: "textures/icon/blocks/gray_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:black_wool",
    displayName: "§fBlack Wool",
    icon: "textures/icon/blocks/black_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:brown_wool",
    displayName: "§fBrown Wool",
    icon: "textures/icon/blocks/brown_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:red_wool",
    displayName: "§fRed Wool",
    icon: "textures/icon/blocks/red_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:orange_wool",
    displayName: "§fOrange Wool",
    icon: "textures/icon/blocks/orange_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:yellow_wool",
    displayName: "§fYellow Wool",
    icon: "textures/icon/blocks/yellow_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:lime_wool",
    displayName: "§fLime Wool",
    icon: "textures/icon/blocks/lime_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:green_wool",
    displayName: "§fGreen Wool",
    icon: "textures/icon/blocks/green_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:cyan_wool",
    displayName: "§fCyan Wool",
    icon: "textures/icon/blocks/cyan_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:light_blue_wool",
    displayName: "§fLight Blue Wool",
    icon: "textures/icon/blocks/light_blue_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:blue_wool",
    displayName: "§fBlue Wool",
    icon: "textures/icon/blocks/blue_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:purple_wool",
    displayName: "§fPurple Wool",
    icon: "textures/icon/blocks/purple_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:magenta_wool",
    displayName: "§fMagenta Wool",
    icon: "textures/icon/blocks/magenta_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  },
  {
    id: "minecraft:pink_wool",
    displayName: "§fPink Wool",
    icon: "textures/icon/blocks/pink_wool_3d.png",
    basePrice: 18,
    stockMax: 1024,
    priceFloorPercent: 0.03,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 512,
    restockIntervalMinutes: 14
  }
];