export const redstone = [
 {
    id: "minecraft:redstone",
    displayName: "§fRedstone",
    icon: "textures/items/redstone_dust.png",
    basePrice: 28,
    stockMax: 512,
    priceFloorPercent: 0.08,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:crafter",
    displayName: "§fCrafter",
    icon: "textures/icon/redstone/crafter_3d.png",
    basePrice: 186,
    stockMax: 256,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 128,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:dispenser",
    displayName: "§fDispenser",
    icon: "textures/icon/redstone/dispenser_3d.png",
    basePrice: 54,
    stockMax: 265,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 128,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:observer",
    displayName: "§fObserver",
    icon: "textures/icon/redstone/observer_3d.png",
    basePrice: 54,
    stockMax: 265,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 128,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:dropper",
    displayName: "§fDropper",
    icon: "textures/icon/redstone/dropper_3d.png",
    basePrice: 50,
    stockMax: 512,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:hopper",
    displayName: "§fHopper",
    icon: "textures/icon/redstone/hopper_3d.png",
    basePrice: 98,
    stockMax: 512,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 256,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:lever",
    displayName: "§fLever",
    icon: "textures/icon/redstone/lever_3d.png",
    basePrice: 8,
    stockMax: 64,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 32,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:piston",
    displayName: "§fPiston",
    icon: "textures/icon/redstone/piston_3d.png",
    basePrice: 54,
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:sticky_piston",
    displayName: "§fSticky Piston",
    icon: "textures/icon/redstone/sticky_piston_3d.png",
    basePrice: 60, 
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:redstone_block",
    displayName: "§fRedstone Block",
    icon: "textures/icon/redstone/redstone_block_3d.png",
    basePrice: 252,
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 1.0,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:redstone_comparator",
    displayName: "§fRedstone Comparator",
    icon: "textures/icon/redstone/redstone_comparator_3d.png",
    basePrice: 68, 
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:redstone_repeater",
    displayName: "§fRedstone Repeater",
    icon: "textures/icon/redstone/redstone_repeater_3d.png",
    basePrice: 62, 
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:redstone_torch",
    displayName: "§fRedstone Torch",
    icon: "textures/icon/redstone/redstone_torch_3d.png",
    basePrice: 10, 
    stockMax: 768,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 386,
    restockIntervalMinutes: 15
  },
  {
    id: "minecraft:tripwire_hook",
    displayName: "§fTripwire Hook",
    icon: "textures/icon/redstone/tripwire_hook_3d.png",
    basePrice: 16, 
    stockMax: 256,
    priceFloorPercent: 0.8,
    priceCeilingPercent: 0.15,
    demandWindowSize: 40,
    restockAmount: 128,
    restockIntervalMinutes: 15
  }
];